### ISSUE TITLE
Support higher refresh rates

### ISSUE THREAD

**Issue by KhelbenArunsun** [jrhollis/jspacman#2]
I just tried the game through itch, and I must say, it plays great, better than other clones! Except for the fact that the game's speed seems to be tied to the refresh rate of the display. 

For example, it runs normally at 60hz, but when I first started it I played at 144hz and died almost instantly. I'd recommend either locking the framerate to the arcade original (which I believe was something like 60.61hz) or allowing the user to choose the framerate. 

As a lefty, WASD as an option would also be appreciated. I may use this as a chance to learn JS and make a pull request at some point.

**Comment by jrhollis** [comment]
Thanks for the report! I've added WASD in-game controls as well as a 60fps throttle (I think... as I don't have any way to recreate a faster frame rate than 60fps).

I took great pains to get this as close to pixel/frame perfect to the original arcade as possible (cutscenes included) with the goal of creating AI agents to train on it... which I only briefly pursued. You might find some code stubbed in for that if you ever peek around in it.
